name: build
run-name: Build xt_tls
on: [pull_request, push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install linux-headers-$(uname -r) libxtables-dev
      - name: Build kernel module
        run: make -C src
      - name: Build xtables extension
        run: make -C ipt
      - name: Install
        run: sudo make install
      - name: "Test: Add iptables rule"
        run: sudo iptables -A FORWARD -p tcp -m tls --tls-host github.com -j ACCEPT
      - name: "Test: Show iptables rules"
        run: sudo iptables -L -v
